### ISSUE TITLE
FEATURE: 채팅 기능 추가

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#11]
## 🛠️ Description for development features
향수 만들기 버튼 클릭 시 '향수 만들기' 로딩 스피너 팝업 구현
향수 만든 후 향수 평가하기 모달 창 구현

## 📝 Todo-lists
- [x] response 5회 이상 시 매 응답마다 팝업창 뜨도록 수정
- [x] 사용자 측 메신저 줄바꿈 수정
- [x] '향수 만들기' 로딩 스피너 팝업 구현
- [x] 향수 평가하기 모달 창 구현
