### ISSUE TITLE
FEATURE: MyPage

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#17]
## 🛠️ Description for development features
마이페이지 UI 작업을 하겠습니다.

## 📝 Todo-lists
- [ ] 내 정보 조회
- [ ] 내 취향 정보 조회 및 수정
- [ ] 프로필 사진 추가 및 수정
- [ ] 커뮤니티 내 글, 내 댓글, 내 좋아요 목록 조회
- [ ] 향수 통계
