### ISSUE TITLE
FEATURE: 캘린더, 채팅 사용자 기능 추가

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#19]
## 🛠️ Description for development features
캘린더 페이지에서 날짜를 선택하면 카드가 뒤집히도록 기능 추가
채팅 페이지에서 챗봇의 메세지 타이핑 효과 기능 추가
좋아하는 향, 싫어하는 향 선택 시 각 향에 tool tip 제공 (간략한 향 설명 추가)

## 📝 Todo-lists
- [x] 캘린더 페이지 날짜 선택 시 카드 반전
- [x] 채팅 페이지 챗봇 메세지 타이핑 효과
- [x] 좋아하는 향, 싫어하는 향 페이지에서 tool tip 추가
