### ISSUE TITLE
FEATURE: 향수 상세페이지 api 연결

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#26]
## 🛠️ Description for development features
향수 상세페이지(모달) 서버 api 연결

## 📝 Todo-lists
- [ ] 캘린더 날짜 클릭 시 향수 상세페이지(모달) 띄우기
- [ ] 향수 상세페이지 api 연결
- [ ] 향수 어코드 chart UI
- [ ] 향수 어코드 chart 연결
