### ISSUE TITLE
FEATURE: 마이페이지 서버 api 연결

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#28]
## 🛠️ Description for development features
마이페이지 서버 api 연결

## 📝 Todo-lists
- [x] 유저 정보 조회
- [x] 유저 이미지 업로드 및 수정
- [x] 취향 정보 조회
- [x] 취향 정보 수정
- [ ] 커뮤니티 기록: 내 글 조회
- [ ] 커뮤니티 기록: 내 댓글 조회
- [ ] 커뮤니티 기록: 내 좋아요 조회
