### ISSUE TITLE
FEATURE: 향수 제작 서버 api 연결

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#36]
## 🛠️ Description for development features
향수 레시피 출력 후 향수 제작 api 요청

## 📝 Todo-lists
- [x]  향수 제작 api 연결
- [x] 향수 레시피 출력 모달 UI 수정
- [x] 향수 레시피 출력 모달 (title, description) 출력 추가
