### ISSUE TITLE
FEATURE: 회원가입/로그인

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#4]
## 🛠️ Description for development features
사용자 회원가입/추가정보/로그인 기능 개발

## 📝 Todo-lists
- [x] 회원가입 UI 구현
- [x] 회원가입 기능 연결
- [x] 로그인 UI 구현
- [x] 로그인 기능 연결
- [x] 추가정보 UI 구현
- [x] 추가정보 기능 연결
