### ISSUE TITLE
REFATOR: 추가정보 코드 리팩토링

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#59]
# 🛠️ Description for refactoring features
회원가입 시 좋아하는 향, 싫어하는 향 선택하는 코드 리팩토링

## 📝 Todo-lists
- [x] 좋아하는 향, 싫어하는 향 선택 값 english -> korea로 수정
- [x] 회원가입 시 선택한 좋아하는 향, 싫어하는 향 그리드에 표시
- [ ] 좋아하는 향으로 선택한 값은 싫어하는 향으로 선택 불가 처리
- [x] 추가정보 수정 기능 (patch)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the scent selection process to use Korean names instead of English, prevent selecting the same scent as both liked and disliked, and implement additional info modification functionality.

You can review changes in this commit: https://github.com/mnmnk43434/4ragrant-SCENTASY_FE-59/commit/d882d8e57bb8ec3f43eda621e6fe1447a7bbc123.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
